#!/bin/bash

# We need two things: chef-solo and git.
# Currently, we don't try to install either for you.

SOLO_SET=""
if [ "$#" -lt "1" ]; then
  SOLO_SET="personal"
else
  SOLO_SET="$1"
fi

BIN_GIT="`which git`"
if [ $? -ne 0 ]; then
  echo "[-] Could not find git"
  exit 1;
else
  GIT_VERSION="`git version | cut -d' ' -f3`"
  echo "[+] Using git $GIT_VERSION from $BIN_GIT"
fi

BIN_SOLO="`which chef-solo`"
if [ $? -ne 0 ]; then
  echo "[-] Could not find chef-solo"
  exit 1;
else
  SOLO_VERSION="`chef-solo --version | cut -d' ' -f2`"
  echo "[+] Using chef-solo $SOLO_VERSION from $BIN_SOLO"
fi

if [ "$SOLO_SET" == "init" ]; then
  echo "[+] Initializing ..."
  # Create the directory which will contain cloned repos etc
  mkdir -p $HOME/.csolo
  # Create directory from where we can run csolo in the future.
  # Also, copy csolo there. Make a backup if it already exists
  mkdir -p $HOME/local/bin
  if [ "$0" != "$HOME/local/bin/csolo" ]; then
    cp --backup=numbered "$0" $HOME/local/bin
  fi
  echo '    Make sure that HOME/local/bin is in your $PATH.'
  echo '    Make sure you have the zip gem installed.'
  # Create scm directory
  mkdir -p $HOME/scm/{code,chef/cookbooks}
  # Create chef directories
  if [ ! -d $HOME/.chef/solo/cookbooks ]; then
    mkdir -p $HOME/.chef/solo/cookbooks
  fi
  if [ ! -d $HOME/.chef/solo/cache ]; then
    mkdir -p $HOME/.chef/solo/cache
  fi
  if [ ! -d $HOME/.chef/solo/cache/backup ]; then
    mkdir -p $HOME/.chef/solo/cache/backup
  fi
  if [ -f solo.rb ]; then
    cp --backup=numbered solo.rb $HOME/.chef/
  fi
  if [ -f solo.json ]; then
    cp --backup=numbered solo.json $HOME/.chef/
  fi
  if [ -f solo.system.json ]; then
    cp --backup=numbered solo.system.json $HOME/.chef/
  fi
  echo "[+] Cloning froschi default cookbook."
  if [ ! -d $HOME/scm/chef/cookbooks/froschi ]; then
    git clone \
      https://github.com/froschi/chef-cookbook-froschi/ \
      $HOME/scm/chef/cookbooks/froschi
  fi
  if [ ! -e $HOME/.chef/solo/cookbooks/froschi ]; then
    ln -sf \
      $HOME/scm/chef/cookbooks/froschi \
      $HOME/.chef/solo/cookbooks/froschi
  fi
  exit 0
fi

SOLO_LOG_LEVEL="info"
SOLO_CONFIG="$HOME/.chef/solo.rb"
SOLO_JSON_PERSONAL="$HOME/.chef/solo.json"
SOLO_JSON_SYSTEM="$HOME/.chef/solo.system.json"

if [ "$SOLO_SET" == "personal" ]; then
  $BIN_SOLO -l $SOLO_LOG_LEVEL -c $SOLO_CONFIG -j $SOLO_JSON_PERSONAL
elif [ "$SOLO_SET" == "system" ]; then
  sudo $BIN_SOLO -l $SOLO_LOG_LEVEL -c $SOLO_CONFIG -j $SOLO_JSON_SYSTEM
else
  echo "[-] Please provide an option: 'system' or 'personal'."
  exit 1
fi

# vim: tabstop=2 shiftwidth=2 expandtab
